spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
server:
  port: 8000


